vim.opt.rtp:prepend(vim.fn.getcwd())
local executor = require("zettypst.executor")
local uv = vim.uv
local root = vim.fn.tempname()
assert(uv.fs_mkdir(root, 448))
local ok, reason = pcall(function()
  local io = executor.io(root)
  local token = assert(io.lock())
  local held, owner = io.lock()
  assert(not held, "lock must be exclusive")
  assert(owner:find("pid " .. uv.os_getpid(), 1, true), "a held lock must name its owner")
  io.unlock(token)
  assert(not uv.fs_stat(root .. "/.zettypst/host.lock"))
  assert(io.read("missing.typ") == vim.NIL)
  io.apply({ kind = "create", path = "a.typ", content = "first\n" })
  assert(io.read("a.typ") == "first\n")
  assert(not pcall(io.apply, { kind = "create", path = "a.typ", content = "clobber" }))
  assert(io.read("a.typ") == "first\n")
  io.apply({ kind = "replace", path = "a.typ", before = "first\n", content = "second\0value" })
  assert(io.read("a.typ") == "second\0value")
  assert(not pcall(io.apply, { kind = "replace", path = "a.typ", before = "stale", content = "clobber" }))
  assert(io.read("a.typ") == "second\0value")
  assert(uv.fs_symlink(root .. "/a.typ", root .. "/alias.typ"))
  local aliased = io.read("alias.typ")
  assert(aliased == "second\0value", "reads must follow symlinks")
  assert(not pcall(io.apply, { kind = "replace", path = "alias.typ", before = aliased, content = "x" }))
  assert(uv.fs_mkdir(root .. "/real", 448))
  assert(uv.fs_symlink(root .. "/real", root .. "/linked"))
  io.apply({ kind = "create", path = "real/b.typ", content = "b" })
  assert(io.read("linked/b.typ") == "b", "reads through symlinked directories must work")
  assert(not pcall(io.apply, { kind = "create", path = "linked/c.typ", content = "c" }))
  vim.cmd.edit(root .. "/a.typ")
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { "modified" })
  assert(not pcall(io.clean, { ["a.typ"] = true }))
  io.clean({ ["unrelated.typ"] = true })
  vim.bo.modified = false
  io.apply({ kind = "delete", path = "a.typ", before = "second\0value" })
  assert(io.read("a.typ") == vim.NIL)
  local scan = assert(uv.fs_scandir(root))
  while true do
    local name = uv.fs_scandir_next(scan)
    if not name then
      break
    end
    assert(not name:match("^%.zettypst%-"), "temporary file leaked")
  end
end)
vim.fn.delete(root, "rf")
assert(ok, reason)
print("passed real file IO, exclusive locks, CAS, symlinks and modified buffers")
