vim.opt.rtp:prepend(vim.fn.getcwd())
local config = require("zettypst.config")
local plugin = require("zettypst")
local cwd = vim.fn.getcwd()
local temp = vim.fn.tempname()
local buf = vim.api.nvim_create_buf(false, false)
vim.fn.mkdir(temp .. "/project/.zettypst", "p")
vim.fn.mkdir(temp .. "/project/notes", "p")
local root = vim.uv.fs_realpath(temp .. "/project")
local ok, reason = pcall(function()
  vim.api.nvim_set_current_dir(root .. "/notes")
  config.setup({})
  assert(plugin.root_dir(buf) == nil, "generic defaults must not discover projects")
  config.setup(require("zettypst.presets.kickstart"))
  assert(plugin.root_dir(buf) == root, "unnamed buffer must discover from cwd")
  vim.api.nvim_buf_set_name(buf, root .. "/notes/new.typ")
  vim.api.nvim_set_current_dir(temp)
  assert(plugin.root_dir(buf) == root, "new file must discover from its path, not cwd")
  vim.api.nvim_set_current_dir(root)
  vim.api.nvim_buf_set_name(buf, temp .. "/outside.typ")
  assert(plugin.root_dir(buf) == nil, "outside file must not select cwd project")
  vim.bo[buf].buftype = "nofile"
  assert(plugin.root_dir(buf) == root, "dashboard must discover from cwd")
  local received
  config.setup({
    root_dir = function(path)
      received = path
      return root .. "/notes/.."
    end,
  })
  assert(plugin.root_dir(buf) == root, "custom root must be canonicalized")
  assert(received == root, "custom resolver must receive cwd for special buffers")
  assert(not pcall(config.setup, { root_dir = true }), "invalid resolver must be rejected")
end)
vim.api.nvim_set_current_dir(cwd)
vim.api.nvim_buf_delete(buf, { force = true })
vim.fn.delete(temp, "rf")
config.setup({})
assert(ok, reason)
print("passed project discovery: defaults, startup, files, dashboard and custom resolver")
