[package]
name = "zettyp-site"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Xinyu Xiang"]
license = "MIT"
repository = "https://github.com/Project-ZetTypst/ZetTypst"
compiler = "0.15.0"
categories = ["model"]
description = "Forester-style cards for ZetTypst Web publication."
keywords = ["zettelkasten", "html", "forester"]
